
package br.com.fiap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11
 * Tue Jun 12 02:15:31 CEST 2018
 * Generated source version: 2.7.11
 */

@XmlRootElement(name = "WhatIsTheAnswerResponse", namespace = "http://fiap.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WhatIsTheAnswerResponse", namespace = "http://fiap.com.br/")

public class WhatIsTheAnswerResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

